project:
  type: book
  output-dir: docs

book:
  title: "Probability (BST 230) Notes"
  author: "Christian Testa"
  chapters:
    - index.qmd
    - week1/week1.qmd
    - week2/week2.qmd

format:
  html:
    theme: style.scss
    number-sections: false
  pdf:
    documentclass: scrreport
  